# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tEXDHafvMacWDYLby6wOo_xm0HQedgN9
"""

!pip install streamlit

import streamlit as st

st.text("Hello World")

